=== leoHerv/firstSite/SITE_hervouet/XML/DTD_JN10.dtd
<!ENTITY % jour
		 "(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|
		 16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)"> 

<!ENTITY % mois "(01|02|03|04|05|06|07|08|09|10|11|12)">


<!ELEMENT jeuxNintendo (Information?,Creation?,Navigation?,a*,p*,div*)>
<!ATTLIST jeuxNintendo id ID #IMPLIED>

<!------------------------------>
<!--Elements de "jeuxNintendo"-->
<!------------------------------>

<!ELEMENT Information (game, div2?)>
<!ATTLIST Information id ID #IMPLIED>

<!ELEMENT Creation (Developer*,Editor*,Director*,Scriptwriter*,Composer*,Producer*)>
<!ATTLIST Creation id ID #IMPLIED>

<!ELEMENT a (picture,#PCDATA)
<!ATTLIST a
	  id ID #IMPLIED
      href CDATA #IMPLIED>

<!ELEMENT picture EMPTY>
<!ATTLIST Creation
      id ID #IMPLIED
      src CDATA #REQUIRED
	  alt CDATA #REQUIRED
	  title CDATA #IMPLIED
	  width CDATA #IMPLIED
	  height CDATA #IMPLIED>

<!ELEMENT span (#PCDATA)
<!ATTLIST span
       class IDREF #IMPLIED
       id ID #IMPLIED>

<!ELEMENT p (#PCDATA,a*)
<!ATTLIST p
       class IDREF #IMPLIED
       id ID #IMPLIED>


<!ELEMENT div (#PCDATA,a*)
<!ATTLIST div
       class IDREF #IMPLIED
       id ID #IMPLIED>


<!----------------------------->
<!--Elements de "Information"-->
<!----------------------------->

<!ELEMENT game (#PCDATA)>
<!ATTLIST game id ID #IMPLIED>

<!ELEMENT div2 (gender+,releaseDate,gameMode?,evaluation?,sales?)
<!ATTLIST div2 
	  class IDREF #IMPLIED
      id ID #IMPLIED>

<!ELEMENT gender (#PCDATA, span*)>
<!ATTLIST gender id ID #IMPLIED>

<!ELEMENT releaseDate (day,month,year, span*,#PCDATA*)>
<!ATTLIST releaseDate id ID #IMPLIED>

<!ELEMENT gameMode (#PCDATA, span*)>
<!ATTLIST gameMode id ID #IMPLIED>

<!ELEMENT engine (#PCDATA, span*)>
<!ATTLIST engine id ID #IMPLIED>

<!ELEMENT evaluation (#PCDATA, span*)>
<!ATTLIST evaluation id ID #IMPLIED>

<!ELEMENT sales (#PCDATA, span*)>
<!ATTLIST sales id ID #IMPLIED>

<!ELEMENT day (%jour;)>
<!ATTLIST day id ID #IMPLIED>

<!ELEMENT month (%mois;)>
<!ATTLIST month id ID #IMPLIED>

<!ELEMENT year (#PCDATA)>
<!ATTLIST year id ID #IMPLIED>

<!-------------------------->
<!--Elements de "Creation"-->
<!-------------------------->

<!ELEMENT Developer (#PCDATA, span*)>
<!ATTLIST Developer id ID #IMPLIED>

<!ELEMENT Editor (#PCDATA, span*)>
<!ATTLIST Editor id ID #IMPLIED>

<!ELEMENT Director (#PCDATA, span*)>
<!ATTLIST Director id ID #IMPLIED>

<!ELEMENT Scriptwriter (#PCDATA, span*)>
<!ATTLIST Scriptwriter id ID #IMPLIED>

<!ELEMENT Composer (#PCDATA, span*)>
<!ATTLIST Composer id ID #IMPLIED>

<!ELEMENT Producer (#PCDATA, span*)>
<!ATTLIST Producer id ID #IMPLIED>

=== leoHerv/firstSite/SITE_hervouet/XML/XML_animal_crossing_page.xml
<!--Les attributs entre parenthèses sont en options -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JN10 SYSTEM "DTD_JN10.dtd">

<jeuxNintendo>

		<div id="navigation">
            <a href="fortnite_page.xhtml">
            <picture src="../../Images/Navigation/arrows_left.png" alt="Fléche Arrière" title="Arrière" width="4%" height="4%"/></a>
            <a href="index.html">
            <picture src="../../Images/Navigation/page_index.png" alt="page_index" title="Home" width="4%" height="4%"/></a>
            <a href="pokemon_epee_page.xhtml">
            <picture src="../../Images/Navigation/arrows_right.png" alt="Fléche Avant" title="Avant" width="4%" height="4%"/></a>
        </div>

	<Information id="information">

		<game>Animal Crossing: New Horizons</game>

		<div>
			<gender><span>Genre :</span> Simulation de vie<gender>
			<releaseDate>
				<span href="color-">Date de sortie : </span>
				<day>20</day>/
				<month>03</month>/
				<year>2020</year>
			</releaseDate>
			<gameMode><span href="color-">Jouabilité :</span> de 1 à 8 joueurs</gameMode>
			<engine><span href="color-">Moteur du jeu :</span> LunchPack</engine>
			<evaluation><span href="color-">Classification :</span> PEGI 3</evaluation>
			<sales><span href="color-">Ventes :</span> 31 180 000</sales>
		</div>

	</Information>

	<Creation id="creation">

		<Developer><span href="color-">Développeur :</span>Nintendo EPD</Developer>
		<!-- <Developer (id="")> </Developer> -->
		<Editor><span href="color-">Éditeur :</span>Nintendo</Editor>
		<!-- <Editor (id="")> </Editor> -->
		<Director><span href="color-">Directeur :</span>Aya Kyogoku</Director>
		<!-- <Director (id="")> </Director> -->
		<Scriptwriter><span href="color-">Scénariste :</span>Nintendo</Scriptwriter>
		<!-- <Scriptwriter (id="")> </Scriptwriter> -->
		<Composer><span href="color-">Compositeur :</span>Sayako Doi, Yasuaki Iwata, Shinobu Nagata, Masato Ohashi, Yumi Takahashi et Kazumi Totaka</Composer>
		<!-- <Composer (id="")> </Composer> -->
		<Producer><span href="color-">Producteur :</span>Hisashi Nogami</Producer>
		<!-- <Producer (id="")> </Producer> -->

	</Creation>

    <a>
		<Picture src="../../Images/Collection/Logo_Animal_Crossing.png" alt="Logo Animal Crossing" 
             title="Logo Animal Crossing" width="40%" height="40%"/></a>
		     <!-- <Picture (id="") src="" alt="" (title="")/> -->

  	<p><a href="https://fr.wikipedia.org/wiki/Animal_Crossing:_New_Horizons">Sources</a></p>
</jeuxNintendo>
